### ISSUE TITLE
"UPDATE REQUIRED" seems to cause export issue

### ISSUE THREAD

**Issue by Ralphi88** [artellblender/auto_rig#26] opened 2019-09-06 16:45 UTC
When I hit the "UPDATE REQUIRED" button to update my rigs from 2.79  to 2.8
it seems to work fine until I try to export the rig (with or without geometry) in "Humanoid" mode.
After export I end up with a fbx that appears to have misscaled and misplaced spine, neck and head bones. I use rigs with 3 spine bones instead of 2 but this hasn't been a problem in 2.79.
"Generic" seems to mess up the rig too but in a different way. "Universal" works but gives me some unwanted/unneeded bones - that's why it would be awesome if "Humanoid" would work
correctly again.  (See test_file attached)

[test_file.zip](https://github.com/artellblender/auto_rig/files/3584838/test_file.zip)

**Comment by artellblender** [comment] 2019-09-11 10:54
Thanks for reporting.
Could you please provide more specific informations to reproduce the issue?
Here is what I tried:
-export as a humanoid for Unity
-import the Fbx back in Blender
-on the left, Auto-Rig Pro armature (original blend file). On the right, imported Fbx in Blender. Looks identical. The root bone is smaller because the bone's tail position is different, but this is only a visual difference, there's no impact on the deformations/rig.

![1](https://user-images.githubusercontent.com/20777939/64691554-35d5dd00-d493-11e9-9ce4-95a8969dca18.png)

**Comment by Ralphi88** [comment] 2019-09-11 14:10
Well yes that is exactly what I did and I ended up with what you see in the image below.
Only difference is that I'm still using version 3.41.57. I will update later and try again. Thanks for testing anyway.
![test](https://user-images.githubusercontent.com/54743780/64704442-9a526580-d4ae-11e9-8bfe-61d8b6cdbd22.JPG)

**Comment by artellblender** [comment] 2019-09-11 14:16
Ah ok, indeed there was a spine bone issue fixed one month ago. A notification email has been sent to users, if you haven't received it make sure to enable "Creator Emails" in your consent page:
https://blendermarket.com/account/privacy-center/consents

**Closed** 2019-09-11 14:16 UTC
Labels: Need informations from user

**Comment by Ralphi88** [comment] 2019-09-11 14:18
Thank you very much.
I love your addon.

**Comment by artellblender** [comment] 2019-09-11 14:21
Glad you enjoy!
Make sure to click "Update Armature" once the new version is installed, to fix the spine issue.
